### ISSUE TITLE
After few calls PooledGMService.getConnection takes forever

### ISSUE THREAD

**Issue by digz6666** [sharneng/gm4java#15]
After few calls it takes forever the get connection from PooledGMService.

**Comment by kennethxu** [comment]
This sounds like a major issue that I'm surprised that there is no additional reports on this. Do yo have some sample code to share? Can you provide more information of how are you using it?

**Comment by digz6666** [comment]
@kennethxu I have added test maven project in following repository: https://github.com/digz6666/gm4java-test

By default max active worker count is 8 and it's not closed when finished processing.
So in test code I've set maxActive to 3 and it stuck on getting new connection from pool, waiting forever.

If I don't change maxActive and get connection more than 8 times it also stuck too.

**Comment by kennethxu** [comment]
In the code, the connection was obtained from service but never closed after use. This is typical connection poll implementation just like JDBC connection pooling, you have to close it for it to return back to the pool. The typical usage pattern:
```java
final GMConnection connection = gmService.getConnection();
try {
    // use the connection to execute one more more GM command.
    return connection.execute(command, argument1, argument2, ...);
} finally {
    connection.close();
}
```
or
If and only if you execute GM command exactly ONCE in the try block, you should just call gmService.execute instead of above code block for simplicity and performance.

**Comment by digz6666** [comment]
@kennethxu Ah I see. As I read from http://kennethxu.blogspot.com/2013/03/integrate-java-and-graphicsmagick.html that I thought I don't have to explicitly close the connection:
```
   1:  final GMConnection connection = service.getConnection();
   2:  try {
   3:      return connection.execute(command, arguments);
   4:  } finally {
   5:      connection.close();
   6:  }
can be simplified to
    return service.execute(command, arguments);
```

**Comment by kennethxu** [comment]
notice the the last line, it uses service.execute instead of connection.execute.

**Comment by digz6666** [comment]
@kennethxu Ah got it, thanks for your clarification :)

**Comment by kennethxu** [comment]
you are welcome! I'm glad that I can be helpful.
