### ISSUE TITLE
License for gm4java

### ISSUE THREAD

**Issue by ptlu** [sharneng/gm4java#8]
I was wondering what the license for gm4java is?  Will there be one posed?

Thank you!

**Comment by norrs** [comment]
@ptlu : Apache 2 license according to pom file: https://github.com/sharneng/gm4java/blob/master/pom.xml 

It would be nice to maybe add a LICENSE file to the repository so it would be easier to find.

**Comment by kennethxu** [comment]
Sorry to catch this late. Yes it is Apache 2, it is in the header of every each source file as well. e.g.: https://github.com/sharneng/gm4java/blob/master/src/main/java/org/gm4java/engine/GMConnection.java

Agreed that we can add a LICENSE file.

**Comment by kennethxu** [comment]
This was merged.
