### ISSUE TITLE
-safe-mode problem

### ISSUE THREAD

**Issue by alizelzele** [sharneng/gm4java#9]
on GraphicsMagick 1.3.23 the code does not work with error message "Error: Unknown option: -safe-mode".
i solved it by just removing `-safe-mode` from `org.gm4java.engine.support.Constants` like this:

        static final String[] GM_COMMAND = new String[]{"gm", "batch", "-escape", "windows", "-feedback", "on", "-pass", "OK", "-fail", "NG", "-prompt", "off", "-echo", "off", "-"};

maybe something deprecated in GraphicsMagick get removed?

**Comment by nachoalonso** [comment]
The `-safe-mode` parameter was removed in GraphicsMagick 1.3.22. See diff at http://hg.graphicsmagick.org/hg/GraphicsMagick/diff/0c27524abb7d/magick/command.c#l1.328

That's why gm4java doesn't work with GraphicsMagick 1.3.22 or above.
